within Buildings.Fluid.SolarCollectors.PVT;
model PVT_test_model

  BaseClasses.EN12975 solCol
    annotation (Placement(transformation(extent={{-12,30},{8,50}})));
  BaseClasses.PVOrientedDCPower pVOrientedDCPower(P_loss_factor=P_loss_factor)
    annotation (Placement(transformation(extent={{68,6},{48,26}})));
  Modelica.Fluid.Interfaces.FluidPort_a port_a1
    "Fluid connector a (positive design flow direction is from port_a to port_b)"
    annotation (Placement(transformation(extent={{-110,-10},{-90,10}})));
  Modelica.Blocks.Interfaces.RealOutput P1                            "Power generated by the photovoltaic installation"
    annotation (Placement(transformation(extent={{90,50},{110,70}})));
  parameter Modelica.Units.SI.Efficiency P_loss_factor=0.14
    "Loss factor of the photovoltaic panel(s)";
equation
  connect(solCol.port_a, port_a1) annotation (Line(points={{-12,40},{-56,40},{
          -56,0},{-100,0}}, color={0,127,255}));
  connect(pVOrientedDCPower.P, P1) annotation (Line(points={{69,16},{84,16},{84,
          60},{100,60}}, color={0,0,127}));
  connect(solCol.T_cell, pVOrientedDCPower.T_cell) annotation (Line(points={{9,
          34},{42,34},{42,9.6},{48,9.6}}, color={0,0,127}));
  annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
        coordinateSystem(preserveAspectRatio=false)));
end PVT_test_model;
