within Buildings.Fluid.Geothermal.Borefields.Validation;
model ConstantHeatInjection_100Boreholes_UnequalSegments
  "Short-term comparison variant of ConstantHeatInjection_100Boreholes: 5 unequal segments (end_length_ratio=0.05) instead of the default 10 equal segments, on a realistic hBor=150m borehole"
  extends ConstantHeatInjection_100Boreholes(
    borHol(
      nSeg=5,
      segRatio={0.05, 0.16794494717703354, 0.5641101056459317,
                0.16794494717703354, 0.05}));

  annotation (Documentation(info="<html>
<p>
Same constant-heat-injection short-term/long-term case as
<a href=\"modelica://Buildings.Fluid.Geothermal.Borefields.Validation.ConstantHeatInjection_100Boreholes\">
Buildings.Fluid.Geothermal.Borefields.Validation.ConstantHeatInjection_100Boreholes</a>
(100 boreholes, <code>hBor=150m</code>, a realistic borehole length - unlike the 18.3m
short sandbox validation case), but with the borehole discretized into 5 unequal
segments (<code>segRatio</code> generated by
<code>pygfunction.utilities.segment_ratios(5, end_length_ratio=0.05)</code>) instead
of the default 10 equal segments.
</p>
<p>
Constant heat injection from <code>t=0</code> makes the initial short-term transient
(the borehole's own thermal capacitances charging up) clearly visible as an early
spike/peak in outlet temperature error between the two discretizations, unlike a
step-response test starting from an already-loaded state - this is the case to use
to find the actual maximum short-term error a given segmentation will produce during
a real simulation.
</p>
</html>"));
end ConstantHeatInjection_100Boreholes_UnequalSegments;
