within Buildings.Fluid.Geothermal.Borefields.Validation;
model Sandbox_UnequalSegments
  "Short-term comparison variant of Sandbox: 5 unequal segments (end_length_ratio=0.05) instead of the default 10 equal segments"
  extends Sandbox(
    borHol(
      nSeg=5,
      segRatio={0.05, 0.16794494717703354, 0.5641101056459317,
                0.16794494717703354, 0.05}));

  annotation (Documentation(info="<html>
<p>
Same short-term validation case as
<a href=\"modelica://Buildings.Fluid.Geothermal.Borefields.Validation.Sandbox\">
Buildings.Fluid.Geothermal.Borefields.Validation.Sandbox</a> (Beier et al. 2011
experiment), but with the borehole discretized into 5 unequal segments
(<code>segRatio</code> generated by
<code>pygfunction.utilities.segment_ratios(5, end_length_ratio=0.05)</code>) instead
of the default 10 equal segments, to directly compare short-term (RC-network)
accuracy between the two discretizations against the same measured reference data.
</p>
<p>
This model is part of the exploration described in
<code>Buildings/Resources/Data/Fluid/Geothermal/ZonedBorefields/unequal_segmentation_exploration.ipynb</code>
and the corresponding plan for unequal segmentation support in ZonedBorefields - the
long-term (g-function/kappa) side of that exploration recommended
<code>nSeg=5</code>/<code>end_length_ratio=0.05</code> as the leading candidate; this
model tests whether that choice also holds up short-term.
</p>
</html>"));
end Sandbox_UnequalSegments;
